---
- hosts: servers
  become: true
  tasks:
    - name: instalacion de dependencias
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: añadir la clave GPG
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: añadir el repositorio de docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: instalar docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: instalar pip
      apt:
        name: "python3-pip"
        state: latest
        update_cache: yes

    - name: instalar docker-py
      pip:
        name: "docker-py"
        state: latest

    - name: levantar el servicio y verificar que esta ok
      service:
        name: docker
        state: started
        enabled: yes

    - name: instalar docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

  handlers:
    - name: reiniciar docker
      service:
        name: docker
        state: restarted
